### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by janat08** [ajnsit/concur-documentation#12]
I willing to assume that although Dom and logic are tightly intertwined after having synthesized an event it's possible to test state of the app even if it doesn't return anything- because you can't get at it besides reading the dom.

I suppose that one could simply just for the testing purposes have the app return state and close it to extract it, is that how you'd go about it, and could you demonstrate it?

**Comment by ajnsit** [comment]
This is related to your [issue on alternative backends](https://github.com/ajnsit/purescript-concur/issues/31). I haven't given much thought to how testing UI components would work. However I think the way to go would be to create a trivial in-memory backend which can be inspected at runtime without having to mess with DOM. I will likely create one myself soon.

**Comment by ajnsit** [comment]
I'll close this issue in favor of the one in the purescript-concur-react repo mentioned above.

**Comment by janat08** [comment]
Any chance that signals could be used to get the proper state of the application though?
