### ISSUE TITLE
Issue with example code?

### ISSUE THREAD

**Issue by drewolson** [ajnsit/concur-documentation#14]
I'm noticing that many examples using `onClick` (among others) don't compile for me as-in. I'm forced to either add a `void` or `unit <$`. For example, the following code doesn't compile:

```purescript
hello :: forall a. Widget HTML a
hello = do
  button [onClick] [text "Say Hello"]
  button' [text "Hello Sailor!"]
```

It compiles with these modifications:

```purescript
hello :: forall a. Widget HTML a
hello = do
  button [void onClick] [text "Say Hello"]
  button' [text "Hello Sailor!"]
```

Is this expected? If so, should I submit a PR for updating the examples?

**Comment by ajnsit** [comment]
Closing this as fixed in the [corresponding PR](https://github.com/ajnsit/concur-documentation/pull/16).
