### ISSUE TITLE
Testing Widgets / Signals

### ISSUE THREAD

**Issue by drewolson** [ajnsit/concur-documentation#17]
Is there a good way to "test" firing a widget or signal? Both to retrieve the resulting view and/or value?

I'm thinking about capabilities similar to [elm-test](https://package.elm-lang.org/packages/elm-explorations/test/latest/Test-Html-Selector)'s HTML modules, but also with the ability to look at the resulting value (and not just the view).

**Comment by drewolson** [comment]
It seems I can use `extract` to access the current value of a `Signal`, or `bind` for `Widget`s, but it would be convenient if there was a way to trigger `onClick` events, etc.

I've been using the functions from [Concur.Core.Discharge](https://pursuit.purescript.org/packages/purescript-concur-core/0.4.2/docs/Concur.Core.Discharge) to get access to the current `HTML`, but some way to validate the structure of an `Array ReactElement` without rendering to a `String` would be fantastic.

**Comment by ajnsit** [comment]
I haven't used elm-test. Can you describe how it works? What would it mean to "fire" a Widget?

**Comment by drewolson** [comment]
I've created an example app to try and demonstrate what I'm describing.

[Here](https://github.com/drewolson/concur-testing/blob/8d3a2784c63e6b2a9d3e91cdae72e6fd6df5a554/src/Main.purs#L11-L16) is a very simple `Signal`. Let's say I want to test it.

First, I can look at the current value of the `Signal` in my test using `extract`. [Here](https://github.com/drewolson/concur-testing/blob/8d3a2784c63e6b2a9d3e91cdae72e6fd6df5a554/test/Main.purs#L23-L26) is the test. This works nicely enough.

Next, I want to look at the view for my `Signal`. [Here](https://github.com/drewolson/concur-testing/blob/8d3a2784c63e6b2a9d3e91cdae72e6fd6df5a554/test/Main.purs#L27-L31) I'm using `dischargePartialEffect` to get access to the view, but it would be really nice if there was some way to make assertions about the view rather than having to render to a `String`.

Finally, I want to simulate an `onClick` event for the `Signal` to verify that the count is incremented. I have a placeholder test [here](https://github.com/drewolson/concur-testing/blob/8d3a2784c63e6b2a9d3e91cdae72e6fd6df5a554/test/Main.purs#L32-L34) but I don't know how to achieve this.

Hope this helps clarify.

**Comment by ajnsit** [comment]
Okay that makes sense. How does Elm-test let you specify which event/prop to trigger on which dom element?

**Comment by drewolson** [comment]
While I haven't used `elm-test` too extensively, here are the key capabilities it exposes that be useful as prior art:

1. [Test.Html.Selector](https://package.elm-lang.org/packages/elm-explorations/test/latest/Test-Html-Selector) allows programmatically walking an HTML structure and focusing on elements (I think lenses may be a good fit here in Purescript).
2. [Test.Html.Event](https://package.elm-lang.org/packages/elm-explorations/test/latest/Test-Html-Event) can be used in conjunction with selectors to fire simulated events at the selected nodes.

Here's a brief example from the docs:

```elm
test "Input produces expected Msg" <|
    \() ->
        Html.input [ onInput Change ] [ ]
            |> Query.fromHtml
            |> Event.simulate (Event.input "cats")
            |> Event.expect (Change "cats")
```

I'm not saying we need exactly these tools, or even something close to this design. But I do think a way to more effectively walk the `Array ReactElement` returned from a widget / signal would be useful as well as a way to create simulated events within widgets or signals.
